#!/bin/bash

echo "Testing Nina Curator V2 API on Vercel..."

# Create a minimal base64 image (1x1 pixel)
BASE64_IMAGE="/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCwAA8A/9k="

# Call the API
curl -X POST https://design-critic-agent.vercel.app/api/nina-curator-v2 \
  -H "Content-Type: application/json" \
  -d "{\"imageData\": \"$BASE64_IMAGE\", \"mode\": \"single\"}" \
  | python3 -m json.tool